'use strict';

/**
 * Render `.specshield.yml` from a structured config object.
 *
 * Hand-rolled YAML so we can interleave comments. The shape is small and
 * stable; using `js-yaml.dump` would give us a clean file but no comments —
 * comments are 80% of the value of the file for users reading it later.
 *
 * Schema (all keys optional except where noted):
 *
 *   {
 *     schemaVersion: 1,
 *     failOnBreaking: true,
 *     severity: 'error',
 *     bdct: {
 *       org: 'acme-pay',                  // required
 *       server: 'https://specshield.io',
 *       environment: 'staging',
 *       provider: { name, spec, branch },
 *       consumer: { name, provider, contract, format }
 *     },
 *     github: { specPath, failOnBreaking, commentOnPr }
 *   }
 */

const fs   = require('fs');
const path = require('path');

const HEADER = [
  '# .specshield.yml — generated by `specshield init`',
  '#',
  '# Picked up automatically by every `specshield` invocation in this directory.',
  '# CLI flags always override values in this file.',
  '# Safe to commit. Never put your API key here — keep it in ~/.specshield/config.json',
  '# or set SPECSHIELD_API_KEY in CI.',
  '',
];

function quoteIfNeeded(v) {
  if (v === null || v === undefined) return null;
  const s = String(v);
  if (/^[\w./@:-]+$/.test(s)) return s;        // safe bare scalar
  return JSON.stringify(s);                    // double-quoted, JSON is YAML-safe
}

function emit(lines, indent, key, value) {
  if (value === null || value === undefined || value === '') return;
  lines.push(`${' '.repeat(indent)}${key}: ${quoteIfNeeded(value)}`);
}

function emitBoolean(lines, indent, key, value) {
  if (value === null || value === undefined) return;
  lines.push(`${' '.repeat(indent)}${key}: ${value ? 'true' : 'false'}`);
}

function emitComment(lines, indent, text) {
  lines.push(`${' '.repeat(indent)}# ${text}`);
}

function blank(lines) {
  if (lines[lines.length - 1] !== '') lines.push('');
}

/**
 * Build the YAML string. Returns the final document including a trailing newline.
 */
function render(config = {}) {
  const lines = [...HEADER];

  emit(lines, 0, 'schemaVersion', config.schemaVersion ?? 1);
  blank(lines);

  // ── Local compare defaults ────────────────────────────────────────────
  emitComment(lines, 0, 'Local compare defaults — used by `specshield compare`.');
  emitBoolean(lines, 0, 'failOnBreaking', config.failOnBreaking ?? true);
  emit       (lines, 0, 'severity',       config.severity       ?? 'error');
  blank(lines);

  // ── BDCT section ──────────────────────────────────────────────────────
  if (config.bdct && Object.keys(config.bdct).length > 0) {
    emitComment(lines, 0, 'BDCT defaults — used by every `specshield bdct ...` command.');
    lines.push('bdct:');
    emit(lines, 2, 'org',         config.bdct.org);
    if (config.bdct.server && config.bdct.server !== 'https://specshield.io') {
      emit(lines, 2, 'server',    config.bdct.server);
    }
    emit(lines, 2, 'environment', config.bdct.environment);

    if (config.bdct.provider) {
      blank(lines);
      emitComment(lines, 2, 'This project publishes a provider spec.');
      lines.push('  provider:');
      emit(lines, 4, 'name',   config.bdct.provider.name);
      emit(lines, 4, 'spec',   config.bdct.provider.spec);
      emit(lines, 4, 'branch', config.bdct.provider.branch);
    }

    if (config.bdct.consumer) {
      blank(lines);
      emitComment(lines, 2, 'This project publishes a consumer contract.');
      lines.push('  consumer:');
      emit(lines, 4, 'name',     config.bdct.consumer.name);
      emit(lines, 4, 'provider', config.bdct.consumer.provider);
      emit(lines, 4, 'contract', config.bdct.consumer.contract);
      emit(lines, 4, 'format',   config.bdct.consumer.format ?? 'OPENAPI');
    }
    blank(lines);
  }

  // ── GitHub App defaults ───────────────────────────────────────────────
  if (config.github && Object.keys(config.github).length > 0) {
    emitComment(lines, 0, 'GitHub App + bdct-action defaults.');
    lines.push('github:');
    emit       (lines, 2, 'specPath',       config.github.specPath);
    emitBoolean(lines, 2, 'failOnBreaking', config.github.failOnBreaking);
    emitBoolean(lines, 2, 'commentOnPr',    config.github.commentOnPr);
    blank(lines);
  }

  // Trim trailing blank lines, ensure exactly one trailing newline.
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  return lines.join('\n') + '\n';
}

/**
 * Write the rendered YAML to `<cwd>/.specshield.yml`. Creates parent dirs
 * if needed (it shouldn't, but defensive). Returns the absolute path written.
 */
function writeProjectConfig(config, cwd = process.cwd()) {
  const target = path.join(cwd, '.specshield.yml');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, render(config), 'utf8');
  return target;
}

/**
 * Render a starter GitHub Actions workflow that uses
 * `specshield26/bdct-action@v1`. Optional output of the wizard.
 */
function renderWorkflow({ kind, providerName, consumerName, providerForConsumer }) {
  const isProvider = kind === 'provider' || kind === 'both';
  const isConsumer = kind === 'consumer' || kind === 'both';

  const lines = [
    '# .github/workflows/specshield-bdct.yml',
    '# Generated by `specshield init`. Edit freely.',
    'name: SpecShield BDCT',
    '',
    'on:',
    '  push:',
    '    branches: [main]',
    '',
    'jobs:',
  ];

  if (isProvider) {
    lines.push(
      '  publish-provider:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: specshield26/bdct-action@v1',
      '        with:',
      '          command: publish-provider',
      `          provider: ${providerName}`,
      '          version: ${{ github.sha }}',
      '          spec: api/openapi.yaml',
      '          env: production',
      '          api-token: ${{ secrets.SPECSHIELD_API_KEY }}',
      '',
      '  gate:',
      '    needs: publish-provider',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: specshield26/bdct-action@v1',
      '        with:',
      '          command: can-i-deploy',
      `          service: ${providerName}`,
      '          version: ${{ github.sha }}',
      '          env: production',
      '          api-token: ${{ secrets.SPECSHIELD_API_KEY }}',
      '',
    );
  }

  if (isConsumer) {
    lines.push(
      '  publish-consumer:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: specshield26/bdct-action@v1',
      '        with:',
      '          command: publish-consumer',
      `          consumer: ${consumerName}`,
      `          provider: ${providerForConsumer}`,
      '          version: ${{ github.sha }}',
      '          contract: contracts/contract.yaml',
      '          api-token: ${{ secrets.SPECSHIELD_API_KEY }}',
      '',
    );
  }

  return lines.join('\n');
}

function writeWorkflow(spec, cwd = process.cwd()) {
  const dir    = path.join(cwd, '.github', 'workflows');
  const target = path.join(dir, 'specshield-bdct.yml');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(target, renderWorkflow(spec), 'utf8');
  return target;
}

module.exports = {
  render,
  writeProjectConfig,
  renderWorkflow,
  writeWorkflow,
};
